# Generated by Django 3.2.16 on 2024-03-09 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CONDUCTORS',
            fields=[
                ('C_NO', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('C_NAME', models.CharField(max_length=50)),
                ('AGE', models.IntegerField()),
                ('SEX', models.CharField(max_length=1)),
                ('JOIN_DATE', models.DateField()),
                ('EXPERIENCE', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Conductor',
                'verbose_name_plural': 'Conductors',
            },
        ),
        migrations.CreateModel(
            name='DRIVERS',
            fields=[
                ('D_NO', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('D_NAME', models.CharField(max_length=50)),
                ('AGE', models.IntegerField()),
                ('SEX', models.CharField(max_length=1)),
                ('JOIN_DATE', models.DateField()),
                ('EXPERIENCE', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
            },
        ),
        migrations.CreateModel(
            name='ROUTES',
            fields=[
                ('ROUTE_NAME', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('SOURCE', models.CharField(max_length=70)),
                ('DESTINATION', models.CharField(max_length=70)),
                ('PICKUP_TIME', models.TimeField()),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
            },
        ),
        migrations.CreateModel(
            name='PASSENGERS',
            fields=[
                ('P_NO', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('P_NAME', models.CharField(max_length=50)),
                ('SEX', models.CharField(max_length=1)),
                ('PICKUP_TIME', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_pickup_time', to='home.routes')),
                ('ROUTE_NAME', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_route', to='home.routes')),
            ],
            options={
                'verbose_name': 'Passenger',
                'verbose_name_plural': 'Passengers',
            },
        ),
        migrations.CreateModel(
            name='BUSES',
            fields=[
                ('LICENSE_PLATE', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('C_NO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.conductors')),
                ('D_NO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.drivers')),
                ('ROUTE_NAME', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.routes')),
            ],
            options={
                'verbose_name': 'Bus',
                'verbose_name_plural': 'Buses',
            },
        ),
    ]
